# Exploring the data prior to modeling
Inspect the dataset to guide model development

In [2]:
# Move the execution of the folder up one directory to place the src in the path
import os
import pandas as pd
os.chdir('..')

In [7]:
import src.common.tools as tools
import matplotlib.pyplot as plt
import src.data.dataio as dataio

config = tools.load_config()
filepath = config["dataprocesseddirectory"] + "train.csv"
[X, y] = dataio.load(filepath)
print(X)

[[ 0.47540328  0.79308916  0.97301085  1.480196  ]
 [-0.7000444   1.44793342 -1.33890804 -1.35148331]
 [-0.81758917 -0.73488078  0.01441033  0.19306904]
 [-0.22986532 -1.17144362  0.63468126  0.96534522]
 [ 1.41576143 -0.08003652  1.14217565  1.09405792]
 [ 1.5333062   0.35652632  1.19856391  0.70791983]
 [ 2.12103004 -0.9531622   1.70605831  1.35148331]
 [ 0.82803759 -0.29831794  0.40912819  0.06435635]
 [-0.46495486  1.01137058 -1.45168457 -1.35148331]
 [-1.28776824  0.79308916 -1.11335498 -1.35148331]
 [ 0.59294805  0.1382449   0.91662259  0.70791983]
 [-1.17022347 -1.17144362  0.35273993  0.57920713]
 [-0.93513393  1.01137058 -1.39529631 -1.22277061]
 [ 2.00348527 -0.08003652  1.53689351  1.09405792]
 [-0.11232056 -0.73488078  0.01441033 -0.06435635]
 [-0.34741009 -0.51659936  0.57829299  0.96534522]
 [ 0.47540328 -1.17144362  0.63468126  0.83663252]
 [ 0.71049282  0.35652632  0.69106952  0.96534522]
 [ 2.35611958  1.66621484  1.42411698  0.96534522]
 [-0.46495486 -1.38972504 -0.0983662  -0.32178174]
 [-1.28776824  0.79308916 -1.28251978 -1.35148331]
 [-1.0526787  -2.26285073 -0.21114273 -0.32178174]
 [-0.58249963  1.44793342 -1.33890804 -1.35148331]
 [ 0.94558236  0.57480774  1.02939912  1.6089087 ]
 [ 0.94558236  0.1382449   0.97301085  1.480196  ]
 [-1.17022347  0.1382449  -1.33890804 -1.35148331]
 [-1.75794731 -0.29831794 -1.39529631 -1.35148331]
 [-0.93513393 -1.17144362 -0.49308406 -0.19306904]
 [ 1.5333062   1.229652    1.25495218  1.6089087 ]
 [ 0.71049282 -0.08003652  0.91662259  0.70791983]
 [ 0.12276898 -0.29831794  0.35273993  0.32178174]
 [-1.17022347 -0.08003652 -1.39529631 -1.35148331]
 [ 1.18067189  0.35652632  1.02939912  1.35148331]
 [-1.0526787   0.35652632 -1.50807284 -1.35148331]
 [-0.11232056 -0.73488078  0.69106952  0.83663252]
 [-0.34741009 -0.73488078  0.18357513  0.06435635]
 [-0.93513393  1.44793342 -1.33890804 -1.09405792]
 [-1.87549208 -0.08003652 -1.56446111 -1.480196  ]
 [ 0.00522421 -0.08003652  0.69106952  0.70791983]
 [-0.81758917  0.79308916 -1.39529631 -1.35148331]
 [ 1.06312713 -0.51659936  0.52190473  0.19306904]
 [ 0.24031375 -0.29831794  0.46551646  0.19306904]
 [ 0.12276898 -1.82628789  0.63468126  0.32178174]
 [-1.0526787   1.229652   -1.39529631 -1.35148331]
 [-0.46495486 -1.60800646  0.0707986   0.06435635]
 [-0.22986532  1.66621484 -1.22613151 -1.22277061]
 [ 0.12276898 -1.82628789  0.0707986  -0.32178174]
 [ 0.94558236 -0.08003652  0.74745779  1.35148331]
 [-0.22986532 -0.29831794  0.18357513  0.06435635]
 [-1.64040254 -1.60800646 -1.45168457 -1.22277061]
 [ 0.24031375 -0.51659936  0.0707986   0.06435635]
 [-0.34741009 -0.29831794 -0.15475446  0.06435635]
 [ 0.24031375 -0.08003652  0.40912819  0.19306904]
 [ 1.76839574 -0.51659936  1.25495218  0.83663252]
 [-0.58249963  0.79308916 -1.22613151 -1.35148331]
 [-0.11232056 -0.51659936  0.69106952  1.480196  ]
 [ 0.35785852 -0.51659936  0.52190473  0.70791983]
 [ 0.35785852  0.79308916  0.86023432  1.35148331]
 [-1.0526787  -0.08003652 -1.28251978 -1.35148331]
 [-1.52285778  0.1382449  -1.33890804 -1.35148331]
 [ 0.71049282 -0.08003652  0.74745779  0.96534522]
 [-0.11232056  2.10277768 -1.50807284 -1.35148331]
 [ 0.00522421  0.35652632  0.52190473  0.70791983]
 [-0.46495486 -1.38972504 -0.04197793 -0.19306904]
 [-0.81758917  2.3210591  -1.33890804 -1.480196  ]
 [ 0.71049282 -0.51659936  0.40912819  0.32178174]
 [ 0.35785852 -1.82628789  0.35273993  0.32178174]
 [-0.11232056 -0.73488078  0.69106952  0.83663252]
 [ 0.59294805 -0.51659936  0.97301085  1.09405792]
 [ 0.59294805  0.35652632  0.35273993  0.32178174]
 [-1.17022347 -1.38972504 -0.32391926 -0.32178174]
 [-1.17022347  1.229652   -1.39529631 -1.480196  ]
 [-0.22986532 -0.51659936  0.35273993  0.06435635]
 [ 0.12276898 -0.73488078  0.69106952  0.45049444]
 [-0.93513393  0.79308916 -1.33890804 -1.35148331]
 [-1.0526787   0.79308916 -1.33890804 -1.35148331]
 [-1.0526787   0.79308916 -1.28251978 -1.09405792]
 [ 0.47540328 -0.73488078  0.57829299  0.70791983]
 [ 0.94558236  0.1382449   0.29635166  0.19306904]
 [-0.46495486  2.53934053 -1.39529631 -1.35148331]
 [-1.52285778  0.79308916 -1.39529631 -1.22277061]
 [ 0.94558236  0.57480774  1.02939912  1.09405792]
 [ 1.5333062  -0.08003652  1.08578738  0.45049444]
 [ 2.12103004  1.66621484  1.59328177  1.22277061]
 [ 1.29821666  0.35652632  0.46551646  0.19306904]
 [ 2.12103004 -0.08003652  1.25495218  1.35148331]
 [-0.93513393  1.66621484 -1.33890804 -1.22277061]
 [ 0.94558236 -1.17144362  1.08578738  0.70791983]
 [-0.22986532 -0.51659936  0.12718687  0.06435635]]

In [6]:
curtest_master = pd.read_csv("./data/processed/curtest_master.csv")
curtest_master

/var/folders/dk/2mw0y5w91dggrsnrpxb04jv80000gn/T/ipykernel_92662/1040074768.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  curtest_master = pd.read_csv("./data/processed/curtest_master.csv")

,testdt,lea,schlcode,year,test_id,score,ach_level,grade,mastid,testid_year,...,LPR,MAG,MLT,MRK,OIP,RAS,SRM,TRA,TRD,year_test
0,2022-05-01,80C,0,2022,MA03,550.0,3,03,10324113.0,MA03_2022,...,0,0,0,0,0,0,0,0,0,2022_MA03
1,2022-05-01,80C,0,2022,RD03,547.0,4,03,10324113.0,RD03_2022,...,0,0,0,0,0,0,0,0,0,2022_RD03
2,2022-05-01,320,316,2022,MA08,547.0,3,08,8928675.0,MA08_2022,...,0,0,0,0,0,0,0,0,0,2022_MA08
3,2022-05-01,320,316,2022,RD08,557.0,3,08,8928675.0,RD08_2022,...,0,0,0,0,0,0,0,0,0,2022_RD08
4,2022-05-01,320,316,2022,SC08,259.0,4,08,8928675.0,SC08_2022,...,0,0,0,0,0,0,0,0,0,2022_SC08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6651491,2018-06-01,010,380,2018,MA03,449.0,3,3.0,8888434.0,MA03_2018,...,0,0,0,0,0,0,0,0,0,2018_MA03
6651492,2018-06-01,010,380,2018,RD03,430.0,1,3.0,8888434.0,RD03_2018,...,0,0,0,0,0,0,0,0,0,2018_RD03
6651493,2018-05-01,920,484,2018,MA07,460.0,4,7.0,9063143.0,MA07_2018,...,0,0,1,0,0,0,0,0,0,2018_MA07
6651494,2018-05-01,920,484,2018,RD07,464.0,4,7.0,9063143.0,RD07_2018,...,0,0,1,0,0,0,0,0,0,2018_RD07
6651495,2018-06-01,36B,0,2018,MTH1,250.0,3,9.0,8946124.0,MTH1_2018,...,0,0,0,0,0,0,0,0,0,2018_MTH1

In [7]:
gpa_master = pd.read_csv("./data/processed/gpa_master.csv")
gpa_master

,lea,schlcode,gpa_unweighted,gpa_weighted,rank_unweighted,rank_weighted,rank_number_unweight,rank_number_weighted,SCHOOL,mastid,bound_for,entry_year,grad_year
0,910,370,3.2245,3.2245,35.0,48.0,204.0,204.0,910370,7254340.0,OTHER,2015.0,2020
1,920,552,4.0000,4.0000,1.0,94.0,427.0,427.0,920552,7193907.0,EMPLOYMENT,2014.0,2020
2,920,436,4.0000,4.0000,1.0,77.0,679.0,679.0,920436,7192199.0,EMPLOYMENT,2015.0,2020
3,920,436,3.4343,3.4343,114.0,174.0,679.0,679.0,920436,7190356.0,PUBLIC SENIOR INSTITUTIONS,2013.0,2020
4,920,441,3.6667,3.6667,251.0,440.0,730.0,730.0,920441,7254467.0,PUBLIC SENIOR INSTITUTIONS,2014.0,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
493867,410,394,1.7778,2.1481,360.0,345.0,403.0,403.0,410394,8011491.0,COMMUNITY & TECHNICAL COLLEGES,2014.0,2018
493868,600,592,3.4333,4.1333,24.0,19.0,378.0,378.0,600592,8988213.0,PUBLIC SENIOR INST -OUT OF NC,2014.0,2018
493869,410,595,2.8077,3.3846,152.0,153.0,301.0,301.0,410595,8011594.0,EMPLOYMENT,2014.0,2018
493870,410,355,1.3704,1.4815,272.0,269.0,292.0,292.0,410355,8011675.0,EMPLOYMENT,2014.0,2018
493871,410,529,2.3448,2.3793,252.0,273.0,327.0,327.0,410529,9055524.0,COMMUNITY & TECHNICAL COLLEGES,2014.0,2018